# Generated by Django 4.2.2 on 2023-06-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style_name", models.CharField(max_length=200)),
                (
                    "style_image",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
                ("tasting_note", models.CharField(max_length=200)),
            ],
        ),
    ]
