# Generated by Django 4.2.2 on 2023-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beer_name", models.CharField(max_length=200)),
                ("brewery_name", models.CharField(max_length=200)),
                (
                    "beer_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/beer_pics"
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style_name", models.CharField(max_length=200)),
                (
                    "style_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/style_images"
                    ),
                ),
                ("tasting_note", models.CharField(max_length=200)),
            ],
        ),
    ]
