# Generated by Django 4.2.2 on 2023-06-22 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="post_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
