# Generated by Django 4.2.2 on 2023-06-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0002_entry_post_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="post_date",
        ),
        migrations.AddField(
            model_name="entry",
            name="beer_style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="entries.style",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="slug",
            field=models.SlugField(default=False, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="title",
            field=models.CharField(default="x", max_length=200),
        ),
        migrations.AddField(
            model_name="entry",
            name="view_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
