# Generated by Django 4.2.2 on 2023-06-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0004_remove_entry_title_entry_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
